### ISSUE TITLE
Delegate in iPhone don't work

### ISSUE THREAD

**Issue by everyonesdesign** [dfcreative/emmy#2]
I faced a case in which emmy#delegate method triggered a function in every single browser but Safari on iPhone.
Not sure whether we can easily recreate it; I think we need to test it deeply.

**Comment by dfcreative** [comment]
We can try to emulate it. But i have to take a look

**Comment by everyonesdesign** [comment]
The problem was caused by iPhone Safari handling 'click' event on interactive elements only ('touchstart' can be used for noninteractive ones).
I think that we shouldn't fix that in the emmy, it's a different level problem.
